package dev.manalith.forge_adapter;

import java.util.List;
import java.util.UUID;

/**
 * ClientDecision
 *
 * Decoded inbound message from the client representing a player decision.
 * Deserialized from the {@code GAME_ACTION} WebSocket envelope defined in
 * {@code docs/PROTOCOL.md}.
 *
 * <p>Instances are enqueued into a {@link NetworkPlayerController}'s inbox
 * by the WebSocket handler and consumed by the corresponding Forge decision
 * callback method.
 *
 * @param actionId   Client-generated UUID for deduplication / idempotency.
 * @param requestId  Echoed requestId from the matching {@link DecisionRequestDTO},
 *                   or {@code null} for unsolicited actions (e.g. CONCEDE).
 * @param seatId     The seat this decision originates from.
 * @param kind       Action kind (mirrors {@code payload.kind} from the protocol,
 *                   e.g. {@code PASS_PRIORITY}, {@code CAST_SPELL}, etc.).
 * @param objectRef  Primary object reference (card ID, permanent ID) if applicable.
 * @param targetIds  Selected target IDs (for CHOOSE_TARGETS, DECLARE_BLOCKERS, etc.).
 * @param intValue   Integer value chosen (for CHOOSE_X, MULLIGAN_DECISION index, etc.).
 * @param rawPayload Full raw JSON payload as a string for future extensibility.
 */
public record ClientDecision(
        UUID actionId,
        UUID requestId,
        UUID seatId,
        String kind,
        String objectRef,
        List<String> targetIds,
        int intValue,
        String rawPayload
) {

    /**
     * Constructs an auto-pass decision with no-op values.
     * Used as a fallback when the client decision times out or the thread
     * is interrupted.
     *
     * @return A synthetic {@code PASS_PRIORITY} decision.
     */
    public static ClientDecision autoPass() {
        return new ClientDecision(
                UUID.randomUUID(),
                null,
                null,
                "PASS_PRIORITY",
                null,
                List.of(),
                0,
                "{\"kind\":\"PASS_PRIORITY\"}"
        );
    }

    /**
     * Returns {@code true} if this decision represents a pass-priority action
     * (either explicit or generated by auto-pass on timeout).
     */
    public boolean isPassPriority() {
        return "PASS_PRIORITY".equals(kind);
    }

    /**
     * Returns {@code true} if this decision represents a concede action.
     */
    public boolean isConcede() {
        return "CONCEDE".equals(kind);
    }
}
