package dev.manalith.forge_adapter;

import java.util.List;
import java.util.UUID;

/**
 * GameDiffDTO
 *
 * Incremental delta between two consecutive game-state revisions, sent as the
 * {@code GAME_DIFF} event defined in {@code docs/PROTOCOL.md}.
 *
 * <p>Clients apply diffs sequentially to their local cached {@link GameStateDTO}
 * to avoid sending a full snapshot on every state change. If a client misses a
 * diff (gap in {@code fromRevision}/{@code toRevision}), it should request a full
 * {@code GAME_STATE} snapshot.
 *
 * <p>When Forge is on the classpath, diffs are generated by
 * {@link GameStateSerializer#serializeDiff(Object, Object)} by comparing two
 * successive {@code forge.game.GameView} snapshots.
 *
 * @param roomId       The room UUID.
 * @param fromRevision The revision this diff applies FROM (exclusive).
 * @param toRevision   The revision this diff applies TO (inclusive).
 * @param changes      List of individual change entries (may be empty for no-ops).
 */
public record GameDiffDTO(
        UUID roomId,
        long fromRevision,
        long toRevision,
        List<DiffEntry> changes
) {

    /** Empty/no-op diff placeholder. */
    public static GameDiffDTO empty(UUID roomId, long revision) {
        return new GameDiffDTO(roomId, revision, revision, List.of());
    }

    // ─── Nested ───────────────────────────────────────────────────────────────

    /**
     * A single field-level change within a game diff.
     *
     * <p>The {@code path} is a dot-separated JSON Pointer-style path identifying
     * the changed field (e.g. {@code "players[0].life"}, {@code "stack[0]"},
     * {@code "battlefield[objectRef=abc123].isTapped"}).
     *
     * @param op       Change operation: {@code "add"}, {@code "remove"}, or {@code "replace"}.
     * @param path     JSON Pointer path to the changed field.
     * @param oldValue Serialized old value (JSON string), or {@code null} for {@code "add"}.
     * @param newValue Serialized new value (JSON string), or {@code null} for {@code "remove"}.
     */
    public record DiffEntry(
            String op,
            String path,
            String oldValue,
            String newValue
    ) {}
}
